
set(BUILD_SHARED_LIBS OFF)
set(SKIP_INSTALL_LIBRARIES ON)
set(SKIP_INSTALL_ALL ON)
set(SKIP_INSTALL_HEADERS ON)
set(SKIP_INSTALL_FILES ON)

set(ZLIB_LIBRARIES "zlibstatic" CACHE STRING "Overriden by CXMF" FORCE)

set(ZLIB_BUILD_EXAMPLES OFF)

set(ASSIMP_BUILD_M3D_IMPORTER OFF)
set(ASSIMP_BUILD_M3D_EXPORTER OFF)
set(ASSIMP_BUILD_USD_IMPORTER OFF)
set(ASSIMP_BUILD_USD_VERBOSE_LOGS OFF)
set(ASSIMP_BUILD_VRML_IMPORTER OFF)
set(ASSIMP_BUILD_USE_CCACHE ON)
set(ASSIMP_HUNTER_ENABLED OFF)
set(ASSIMP_BUILD_FRAMEWORK OFF)
set(ASSIMP_DOUBLE_PRECISION OFF)
set(ASSIMP_OPT_BUILD_PACKAGES OFF)
set(ASSIMP_ANDROID_JNIIOSYSTEM OFF)
set(ASSIMP_NO_EXPORT ON)
set(ASSIMP_BUILD_ASSIMP_TOOLS OFF)
set(ASSIMP_BUILD_SAMPLES OFF)
set(ASSIMP_BUILD_TESTS OFF)
set(ASSIMP_COVERALLS OFF)
set(ASSIMP_INSTALL OFF)
set(ASSIMP_WARNINGS_AS_ERRORS ON)
set(ASSIMP_ASAN OFF)
set(ASSIMP_UBSAN OFF)
set(ASSIMP_BUILD_DOCS OFF)
set(ASSIMP_INJECT_DEBUG_POSTFIX ON)
set(ASSIMP_IGNORE_GIT_HASH ON)
set(ASSIMP_BUILD_ZLIB OFF)
set(ASSIMP_INSTALL_PDB OFF)
set(ASSIMP_BUILD_ASSIMP_VIEW OFF)
set(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF)
set(ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT OFF)
set(ASSIMP_BUILD_GLTF_IMPORTER ON)
set(ASSIMP_BUILD_FBX_IMPORTER ON)

set(wxBUILD_SHARED OFF)
set(wxBUILD_SAMPLES OFF)
set(wxBUILD_TESTS OFF)
set(wxBUILD_DEMOS OFF)
set(wxBUILD_BENCHMARKS OFF)
set(wxBUILD_INSTALL OFF)
set(wxBUILD_STRIPPED_RELEASE_DEFAULT ON)
set(wxUSE_UNICODE_UTF8 ON)



FetchContent_Declare(
	zlib
	GIT_REPOSITORY	https://github.com/madler/zlib.git
	GIT_TAG			51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf # 1.3.1
	OVERRIDE_FIND_PACKAGE
)
FetchContent_Declare(
	assimp
	GIT_REPOSITORY	https://github.com/assimp/assimp.git
	GIT_TAG			fb375dd8c0a032106a2122815fb18dffe0283721 # 6.0.2
)
FetchContent_Declare(
	wxWidgets
	GIT_REPOSITORY	https://github.com/wxWidgets/wxWidgets.git
	GIT_TAG			49c6810948f40c457e3d0848b9111627b5b61de5 # 3.3.1
)

FetchContent_MakeAvailable(zlib assimp wxWidgets)
